### ISSUE TITLE
empty value causes parsing error

### ISSUE THREAD

**Issue by leehaoze** [RealAlexandreAI/json-repair#13]
When JSON contains an empty value (two consecutive quotation marks), it results in a parsing error for that value.

The `"Incorrect key-value pair {"key":"",}`  in the example actually leads to an incorrect parsing result: `{"key":",}"}`

I have found the code that leads to this issue, but I'm not sure what the original purpose of this code was：

https://github.com/RealAlexandreAI/json-repair/blob/d67efee3d212066182b1327122f4dcc995e2a971/jsonrepair.go#L282-L284

**Comment by RealAlexandreAI** [comment]
Fixed in v0.0.8.
