### ISSUE TITLE
version mismatch between releases and `jsonrepair -v` output

### ISSUE THREAD

**Issue by luckman212** [RealAlexandreAI/json-repair#15]
https://github.com/RealAlexandreAI/json-repair/blob/3cc8f746d3d97d5761c09fd020abd27c46635545/cli/jsonrepair-cli.go#L11

Is the CLI pinned at v0.0.8 or does this const just need to be updated?

```
$ jsonrepair -v
Version: 0.0.8
```

**Comment by RealAlexandreAI** [comment]
It will be fixed in the next release. I haven't found a good method to generate semantic versioning in the GitHub CI. PR is welcome.

**Comment by luckman212** [comment]
Thanks. I don't have the answer either, but I will see if I can come up with it.

**Comment by RealAlexandreAI** [comment]
fixed in 0.0.11.
