### ISSUE TITLE
go.mod refers to Go version 1

### ISSUE THREAD

**Issue by ccoVeille** [RealAlexandreAI/json-repair#2]
## Describe the bug

go.mod refers to Go 1

https://github.com/RealAlexandreAI/json-repair/blob/a2b6f9452be4618bcf570ec5351aaadfc600e6ae/go.mod#L3

So around 2012 https://go.dev/doc/devel/release#go1

### Expected behavior
Use Go 1.18 at least, even if I would prefer go 1.22

**Comment by RealAlexandreAI** [comment]
This library maintains compatibility with Go and has zero dependencies. Its typical use cases may be in automation, workflow, and sandbox environments.

**Comment by ccoVeille** [comment]
Thanks for explaining the reason you somehow decided to force it to `go 1` in the file, but then I don't understand the logic of maintaining compatibility.

Do you mean you expect your code to be valid with go 1? The code evolved a lot.

I mean here you are using [json.Valid](https://pkg.go.dev/encoding/json#Valid) that can be used only from go1.9

https://github.com/RealAlexandreAI/json-repair/blob/c7e16e1c72225b88f79c96b19e736d275b122c63/jsonrepair.go#L20

I found this one pretty quickly, I'm sure there are other examples

**Comment by RealAlexandreAI** [comment]
Thank you for your reply. It seems I have misunderstood the compatibility of Go. I will try to understand this aspect as soon as possible. I also welcome you to submit a pull request (PR), and make sure to keep the minimum version requirement as low as possible.

**Comment by ccoVeille** [comment]
I created https://github.com/RealAlexandreAI/json-repair/pull/10 to help you to understand the minimal version concept
