### ISSUE TITLE
Test_Example is not a test

### ISSUE THREAD

**Issue by ccoVeille** [RealAlexandreAI/json-repair#5]
This code doesn't use `t` variable

https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair_test.go#L15-L20

I'm unsure what you wanted to test, so how I would suggest you to fix it.

**Comment by RealAlexandreAI** [comment]
I will fix it. The superfluous items in local development.
