### ISSUE TITLE
contains method should not exist

### ISSUE THREAD

**Issue by ccoVeille** [RealAlexandreAI/json-repair#6]
https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair.go#L457

You can rely on strings lib https://pkg.go.dev/strings#Contains

You are already using it, BTW

**Comment by RealAlexandreAI** [comment]
This is a known issue, but I want to achieve an effect of 'Contains', similar to the Java List, using an explicit type.

**Comment by RealAlexandreAI** [comment]
If there are no prerequisites concerning dependencies, I would use lo.Contains.

**Comment by ccoVeille** [comment]
I think you meant `strings.Contains`

Go comes with all its packages, and you are already using `strings` package

https://github.com/RealAlexandreAI/json-repair/blob/2ca7b07c5771acd8a11925c7c29520c5b88d186e/jsonrepair.go#L7

Everyone uses it, even you

https://github.com/search?q=repo%3ARealAlexandreAI%2Fjson-repair+strings.&type=code

![image](https://github.com/RealAlexandreAI/json-repair/assets/3875889/acd3b638-9252-43ba-a79b-7a80e76d5c5f)

This is not a dependency, it's a Go package.

**Comment by ccoVeille** [comment]
I'm unsure why you want to achieve the zero dependencies or the fewest dependency as possible. It's ok to target to do not depend on external dependencies, but here you are forbidding yourself to use golang lib.

It can only be accepted in the logic of keeping the size of the final Go binary small, but your lib will be imported, you can be sure they will use `strings` package.

So here, considering you are already importing `strings`, your `contains` method adds size to the binary.

**Comment by RealAlexandreAI** [comment]
In this scenario, I would like the `contains` method signature to accept an array instead of 2 string.

**Comment by ccoVeille** [comment]
https://pkg.go.dev/strings#ContainsAny

or you could import bytes to use `bytes#ContainsAny`, but it would bring `bytes` package

https://pkg.go.dev/bytes#ContainsAny

**Comment by ccoVeille** [comment]
I made some checks

Current code

```console
❯ go build -v . ; du -b cli
2528249	cli
```

By using strings.ContainsAny

```console
$ go build -v . ; du -b cli
2528690	cli
```

But I won't expect anyone to look for this, but maybe you care.

**Comment by RealAlexandreAI** [comment]
https://github.com/RealAlexandreAI/json-repair/commit/0d3bd4b08e5ea71ef269b8886f67eebf69a3cc07 I've reviewed the go doc, perhaps bytes.IndexByte would be a better choice.
