### ISSUE TITLE
RepairJSON signature should return an error

### ISSUE THREAD

**Issue by ccoVeille** [RealAlexandreAI/json-repair#7]
https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair.go#L16
https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair.go#L57

Right now, you are ignoring error handling in various place

https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair.go#L27
https://github.com/RealAlexandreAI/json-repair/blob/c3d3c7e806da0cd607a1cbbe24b922da01cd3865/jsonrepair.go#L22

I didn't check further, but I would expect `parseJson` to also return an error

**Comment by RealAlexandreAI** [comment]
I will continue to pay attention to more scenarios, methods in the form of MustXXX are an option, but I currently want to make them the default. For example, they will be used quickly in my next project, used in Function Call -> Agent -> Multi-Agents.

**Comment by RealAlexandreAI** [comment]
fixed

**Comment by ccoVeille** [comment]
Fixed with e34ac0d56bb3f9c2de64ef3715987b2f08170e46

**Comment by ccoVeille** [comment]
One remark, I don't get why the MustXXX don't simply call the XXX

**Comment by RealAlexandreAI** [comment]
I have observed this situation, but the tolerance for panic and the potential for more errors (although they have not yet occurred in the test cases) leads me to temporarily reuse this code. In a trusted environment, such as https://github.com/RealAlexandreAI/sticky-hand and https://github.com/RealAlexandreAI/io-sankey, I would use it directly. Perhaps only a few people hope to use it this way, so incompatibility modifications between these two methods in the future can be understood.
